version: '3.8'
services:
  notebook-service:
    build:
      context: ./services/notebook-service
    container_name: notebook-service
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./services/notebook-service:/app:delegated
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8001/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
