name: Notebook Service CI

on:
  push:
    paths:
      - 'services/notebook-service/**'
  pull_request:
    paths:
      - 'services/notebook-service/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -r services/notebook-service/requirements.txt
      - name: Run tests
        run: |
          . .venv/bin/activate
          pytest -q
